# ==========================================
# CẤU HÌNH DỰ ÁN GOLD-FORECAST
# ==========================================
project_name: "Gold-Forecast-Pro"
version: "1.0.0"
seed: 42

paths:
  raw_data: "data/raw/"
  processed_data: "data/processed/"
  final_data: "data/final/"
  model_save: "artifacts/models/"
  figures_save: "artifacts/figures/"
  logs: "logs/"

data:
  fred_api_key: "YOUR_FRED_API_KEY_HERE"

  start_date: "2000-01-01"
  target_col: "Close"


  market_tickers:
    Gold: "GC=F"
    DXY: "DX-Y.NYB"
    SP500: "^GSPC"
    Oil: "CL=F"
    Silver: "SI=F"

  macro_indicators:
    CPI: "CPIAUCSL"
    Fed_Rate: "FEDFUNDS"
    US10Y: "DGS10"
    M2: "M2SL"
    Real_Rate: "REAINTRATREARAT10Y"

processing:
  window_size: 60
  forecast_horizon: 30
  test_size: 0.2
  scaler_type: "minmax"

model:
  name: "Hybrid_Gold_Forecast_V1"
  input_dim: "auto"
  hidden_dim: 64
  num_layers: 2
  output_dim: 1
  dropout: 0.2

models_config:
  short_term:
    name: "Gold_Short_5D"
    forecast_horizon: 5
    window_size: 30
    hidden_dim: 64
    dropout: 0.1
    learning_rate: 0.001

  medium_term:
    name: "Gold_Medium_15D"
    forecast_horizon: 15
    window_size: 60
    hidden_dim: 96
    dropout: 0.2
    learning_rate: 0.0008

  long_term:
    name: "Gold_Long_30D"
    forecast_horizon: 30
    window_size: 90
    hidden_dim: 128
    dropout: 0.3
    learning_rate: 0.0005

  semi_annual:
    name: "Gold_6Month"
    forecast_horizon: 126
    window_size: 180
    hidden_dim: 128
    dropout: 0.3
    learning_rate: 0.0005


training:
  batch_size: 32
  epochs: 100
  learning_rate: 0.001
  patience: 10
  device: "auto"
  loss_function: "mse"